"""Windows issue #8 regression through the real launcher/native file dialog.

Uses only Python's standard library. Requires an interactive Windows desktop
and the owner's USA ROM. Never pre-creates rom.cfg or places a ROM beside the
executable. Installs, screenshots and logs remain under ignored captures/.
Use --expect-broken with the original v1.7.0 package to prove the regression.
"""
import argparse
import ctypes as c
from ctypes import wintypes as w
import hashlib
import json
import os
from pathlib import Path
import shutil
import subprocess
import tempfile
import time

ROOT = Path(__file__).resolve().parents[1]


class Desktop:
    def __init__(self):
        self.user = c.WinDLL("user32", use_last_error=True)
        self.callback = c.WINFUNCTYPE(w.BOOL, w.HWND, w.LPARAM)
        for name, args in (
            ("EnumWindows", [self.callback, w.LPARAM]),
            ("EnumChildWindows", [w.HWND, self.callback, w.LPARAM]),
            ("GetWindowThreadProcessId", [w.HWND, c.POINTER(w.DWORD)]),
            ("GetClassNameW", [w.HWND, w.LPWSTR, c.c_int]),
            ("GetWindowTextW", [w.HWND, w.LPWSTR, c.c_int]),
            ("GetDlgCtrlID", [w.HWND]),
            ("IsWindowVisible", [w.HWND]),
            ("SendMessageW", [w.HWND, w.UINT, w.WPARAM, w.LPARAM]),
            ("PostMessageW", [w.HWND, w.UINT, w.WPARAM, w.LPARAM]),
        ):
            getattr(self.user, name).argtypes = args
        self.user.SendMessageW.restype = w.LPARAM

    def windows(self, parent=None):
        found = []

        @self.callback
        def visit(hwnd, _):
            pid = w.DWORD()
            cls = c.create_unicode_buffer(256)
            title = c.create_unicode_buffer(1024)
            self.user.GetWindowThreadProcessId(hwnd, c.byref(pid))
            self.user.GetClassNameW(hwnd, cls, len(cls))
            self.user.GetWindowTextW(hwnd, title, len(title))
            if self.user.IsWindowVisible(hwnd):
                found.append((hwnd, pid.value, cls.value, title.value,
                              self.user.GetDlgCtrlID(hwnd)))
            return True

        if parent:
            self.user.EnumChildWindows(parent, visit, 0)
        else:
            self.user.EnumWindows(visit, 0)
        return found

    @staticmethod
    def wait_for(check, proc, label):
        deadline = time.monotonic() + 25
        while time.monotonic() < deadline:
            result = check()
            if result:
                return result
            assert proc.poll() is None, f"Process exited while waiting for {label}"
            time.sleep(.05)
        raise AssertionError(f"Timed out waiting for {label}")

    def choose_rom(self, proc, path):
        dialog = self.wait_for(
            lambda: next((x[0] for x in self.windows()
                          if x[1] == proc.pid and x[2] == "#32770"), None),
            proc, "native ROM file dialog")
        if path == "cancel":
            self.user.PostMessageW(dialog, 0x0111, 2, 0)
            return
        edit = self.wait_for(
            lambda: next((x[0] for x in self.windows(dialog)
                          if x[2] == "Edit" and x[4] == 1148), None),
            proc, "native file-name input")
        value = c.create_unicode_buffer(str(path))
        self.user.SendMessageW(edit, 0x000C, 0, c.cast(value, c.c_void_p).value)
        self.user.PostMessageW(dialog, 0x0111, 1, 0)
        self.wait_for(lambda: not any(x[0] == dialog for x in self.windows()),
                      proc, "native file dialog dismissal")

    def close_launcher(self, proc):
        window = self.wait_for(
            lambda: next((x[0] for x in self.windows()
                          if x[1] == proc.pid and "Launcher" in x[3]), None),
            proc, "launcher window")
        # The same WM_CLOSE generated by the title-bar X.
        self.user.PostMessageW(window, 0x0010, 0, 0)


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--source", type=Path, default=ROOT / "build",
                        help="Packaged install or build with runtime DLLs staged")
    parser.add_argument("--rom", type=Path, default=ROOT / "fzero.sfc")
    parser.add_argument("--output", type=Path)
    parser.add_argument("--expect-broken", action="store_true")
    args = parser.parse_args()
    assert os.name == "nt", "Requires an interactive Windows desktop"
    source, original_rom = args.source.resolve(), args.rom.resolve()
    root = args.output.resolve() if args.output else Path(tempfile.mkdtemp(
        prefix="rom-persistence-", dir=ROOT / "captures"))
    root.mkdir(parents=True, exist_ok=True)
    desktop = Desktop()
    results = []
    base_env = {k: v for k, v in os.environ.items()
                if not k.startswith(("FZERO_", "SNESRECOMP_", "SDL_", "LNG_"))}
    # Prove the installation contains its dependencies without developer PATH.
    base_env.update(PATH=os.environ["SystemRoot"] + r"\System32;" + os.environ["SystemRoot"],
                    SDL_AUDIODRIVER="dummy", SNESRECOMP_AUTOCLOSE_FRAMES="120")

    def cache(install):
        path = install / "rom.cfg"
        return path.read_text().strip() if path.exists() else None

    def run(install, name, *, pick=None, close=False, cwd=None):
        shot = install / f"{name}.png"
        assert not shot.exists(), f"Use a fresh output directory: {shot}"
        script = "size:1100x880;wait:120;"
        if pick is not None:
            script += "click:220,555;wait:240;"
        script += f"shot:{shot.name};"
        script += "wait:1800;quit" if close else "click:970,820;wait:120;quit"
        env = dict(base_env, LNG_SCRIPT=script, SNESRECOMP_SAVE_ROOT="saves")
        log_path = install / f"{name}.log"
        with log_path.open("w") as log:
            proc = subprocess.Popen([str(install / "FZeroSNESRecomp.exe")],
                                    cwd=cwd or root, env=env, stdout=log, stderr=log)
            try:
                if pick is not None:
                    desktop.choose_rom(proc, pick)
                if close:
                    desktop.wait_for(shot.exists, proc, "selected ROM screenshot")
                    desktop.close_launcher(proc)
                code = proc.wait(timeout=45)
            finally:
                if proc.poll() is None:
                    proc.kill()
                    proc.wait()
        text = log_path.read_text(errors="replace")
        assert code == 0, (name, code, text[-3000:])
        assert shot.is_file(), name
        played = "simulation=120" in text
        results.append(dict(case=str(install.relative_to(root)), step=name,
                            played=played, cache=cache(install)))
        print(f"{install.parents[1].name}/{name}: played={played}, cache={cache(install)!r}", flush=True)
        return played

    for exit_mode in ("play", "close"):
        case = root / exit_mode
        install = case / "Decomp Recomp Ports Remakes/FZeroSNESRecomp"
        install.mkdir(parents=True, exist_ok=False)
        shutil.copy2(source / "FZeroSNESRecomp.exe", install)
        for dll in source.glob("*.dll"):
            shutil.copy2(dll, install)
        shutil.copytree(source / "assets", install / "assets")
        library = case / "External ROM Library"
        library.mkdir()
        rom = library / "F-Zero (USA).sfc"
        shutil.copy2(original_rom, rom)
        assert not list(install.glob("*.sfc")) and cache(install) is None
        played = run(install, "select", pick=rom, close=exit_mode == "close")
        assert played == (exit_mode == "play")
        if args.expect_broken:
            assert cache(install) is None, "Expected original missing-cache defect"
            assert not run(install, "restart")
            continue
        assert Path(cache(install)).samefile(rom), "Actual selection was not persisted"
        assert run(install, "restart-1")
        assert run(install, "restart-2", cwd=os.environ["TEMP"])
        if exit_mode == "close":
            assert not run(install, "cancel", pick="cancel", close=True)
            assert Path(cache(install)).samefile(rom)
            bad = library / "Not F-Zero.sfc"
            bad.write_bytes(b"not a supported cartridge" * 1024)
            assert not run(install, "invalid", pick=bad, close=True)
            assert Path(cache(install)).samefile(rom)
            assert run(install, "after-invalid")
            moved = library / "Moved F-Zero (USA).sfc"
            rom.rename(moved)
            assert not run(install, "missing-rom")
            assert not run(install, "select-moved", pick=moved, close=True)
            assert Path(cache(install)).samefile(moved)
            assert run(install, "after-move")
    report = dict(expected_broken=args.expect_broken,
                  executable_sha256=hashlib.sha256((source / "FZeroSNESRecomp.exe").read_bytes()).hexdigest(),
                  source=str(source), results=results)
    (root / "results.json").write_text(json.dumps(report, indent=2) + "\n")
    print(f"{'REPRODUCED' if args.expect_broken else 'PASS'}: {root}", flush=True)


if __name__ == "__main__":
    main()
